# Generated by Django 2.0.4 on 2018-04-22 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('numero_chamada', models.IntegerField()),
                ('ra', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=85)),
                ('celular', models.CharField(max_length=15)),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'db_table': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='Alunotarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.CharField(max_length=1)),
                ('id_aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Aluno')),
            ],
            options={
                'db_table': 'AlunoTarefa',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=85)),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Professorturma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=25)),
                ('id_professor', models.ForeignKey(db_column='id_professor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor')),
            ],
            options={
                'db_table': 'ProfessorTurma',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('email', models.CharField(blank=True, max_length=85, null=True)),
                ('celular', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Responsavel',
            },
        ),
        migrations.CreateModel(
            name='Responsaveltarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualizado', models.IntegerField()),
                ('id_responsavel', models.ForeignKey(db_column='id_responsavel', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Responsavel')),
            ],
            options={
                'db_table': 'ResponsavelTarefa',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('prazo', models.DateField()),
                ('slug', models.SlugField(max_length=20)),
                ('id_professor', models.ForeignKey(db_column='id_professor', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Professor')),
            ],
            options={
                'db_table': 'Tarefa',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=1)),
                ('nivel', models.CharField(max_length=35)),
                ('serie', models.IntegerField()),
                ('identificador', models.CharField(max_length=1)),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.AlterUniqueTogether(
            name='turma',
            unique_together={('turno', 'nivel', 'serie', 'identificador')},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='responsaveltarefa',
            name='id_tarefa',
            field=models.ForeignKey(db_column='id_tarefa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tarefa'),
        ),
        migrations.AddField(
            model_name='professorturma',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AddField(
            model_name='alunotarefa',
            name='id_tarefa',
            field=models.ForeignKey(db_column='id_tarefa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tarefa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_responsavel',
            field=models.ForeignKey(db_column='id_responsavel', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Responsavel'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Turma'),
        ),
        migrations.AlterUniqueTogether(
            name='responsaveltarefa',
            unique_together={('id_responsavel', 'id_tarefa')},
        ),
        migrations.AlterUniqueTogether(
            name='professorturma',
            unique_together={('id_professor', 'id_turma')},
        ),
        migrations.AlterUniqueTogether(
            name='alunotarefa',
            unique_together={('id_aluno', 'id_tarefa')},
        ),
        migrations.AlterUniqueTogether(
            name='aluno',
            unique_together={('id_turma', 'numero_chamada')},
        ),
    ]
