# Generated by Django 2.0.4 on 2018-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunotarefa',
            name='visto',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
